#!/usr/bin/env python3
"""Generate an Arabic .po file for Al-Baron UI strings.

Reads the exact source strings extracted from templates/controllers
(/tmp/strings.json) plus extra route titles, maps each to Arabic via AR,
and writes a .po with byte-faithful msgids. Warns on any unmapped source.
"""
import json, os, sys

AR = {
    "@count results": "@count نتيجة",
    "A controlled workflow, quarry to quay": "سير عمل محكوم، من المحجر إلى الميناء",
    "A heritage of stone, refined for the world’s finest projects.": "إرثٌ من الحجر، مصقولٌ لأرقى المشاريع في العالم.",
    "A material with centuries of character.": "مادةٌ تحمل طابعاً يمتدّ عبر القرون.",
    "A reply from our export team, typically within one business day": "ردٌّ من فريق التصدير لدينا، عادةً خلال يوم عمل واحد",
    "A selection of international projects finished with Al-Baron natural stone and marble — from hotel facades to private interiors.": "مجموعة مختارة من المشاريع الدولية المنفَّذة بحجر ورخام البارون الطبيعي — من واجهات الفنادق إلى التصاميم الداخلية الخاصة.",
    "A vertically integrated stone operation — from quarry to quay — built to hold colour, dimension and finish across the most demanding international projects.": "عمليةٌ متكاملة رأسياً — من المحجر إلى الميناء — مصمَّمة للحفاظ على اللون والأبعاد والتشطيب في أكثر المشاريع الدولية تطلُّباً.",
    "Al-Baron Palestinian stone": "حجر البارون الفلسطيني",
    "Al-Baron location": "موقع البارون",
    "Al-Baron natural stone": "حجر البارون الطبيعي",
    "Al-Baron stone production": "إنتاج حجر البارون",
    "All Projects": "جميع المشاريع",
    "All rights reserved.": "جميع الحقوق محفوظة.",
    "Announcements, trade-show appearances and milestones from Al-Baron — Palestinian natural stone for the world.": "إعلانات ومشاركات في المعارض ومحطات بارزة من البارون — حجرٌ فلسطيني طبيعي للعالم.",
    "Applications": "الاستخدامات",
    "Asia": "آسيا",
    "Authentic Palestinian origin": "أصلٌ فلسطيني أصيل",
    "Authenticity": "الأصالة",
    "Available dimensions": "الأبعاد المتوفّرة",
    "Back to News": "العودة إلى الأخبار",
    "Because we control the full journey — extraction, sawing, finishing, inspection and export packing — what you specify is exactly what arrives on site.": "لأننا نتحكّم في الرحلة الكاملة — الاستخراج والنشر والتشطيب والفحص والتغليف للتصدير — فإن ما تحدّده هو تماماً ما يصل إلى الموقع.",
    "Bethlehem stone": "حجر بيت لحم",
    "Bethlehem · Palestine · Since 1998": "بيت لحم · فلسطين · منذ 1998",
    "Bethlehem, Palestine": "بيت لحم، فلسطين",
    "Block Sawing": "نشر الكتل",
    "Blocks are hand-selected at the quarry for colour, density and character.": "تُنتقى الكتل يدوياً في المحجر حسب اللون والكثافة والطابع.",
    "Breadcrumb": "مسار التنقّل",
    "Bridge cutters size slabs and tiles to precise architectural specifications.": "تقصّ آلات الجسر الألواح والبلاط وفق مواصفات معمارية دقيقة.",
    "Bring authentic Palestinian stone to your project.": "أضِف الحجر الفلسطيني الأصيل إلى مشروعك.",
    "Browse our export range of natural Palestinian stone and marble. Filter by material, colour, finish and application to find the right surface for your project.": "تصفّح مجموعة التصدير من الحجر والرخام الفلسطيني الطبيعي. صفِّ النتائج حسب المادة واللون والتشطيب والاستخدام للعثور على السطح المناسب لمشروعك.",
    "Browse the Range": "تصفّح المجموعة",
    "Built for Export Confidence": "مصمَّمٌ لثقة التصدير",
    "Calibrated thickness": "سماكةٌ معايَرة",
    "Calibrated thickness, consistent colour and repeatable finishes, held to tolerance on every order, large or small.": "سماكةٌ معايَرة ولونٌ متناسق وتشطيباتٌ قابلة للتكرار، تُحفظ ضمن التفاوتات في كل طلب، كبيراً كان أم صغيراً.",
    "Case Studies": "دراسات حالة",
    "Project Examples": "نماذج مشاريع",
    "Illustrative project concepts in Bethlehem, Ramallah, Hebron and Nablus, showing local uses of natural stone and marble.": "تصورات توضيحية لمشاريع في بيت لحم ورام الله والخليل ونابلس، تبرز استخدامات الحجر الطبيعي والرخام محليا.",
    "Certificates and technical documentation are provided on request and published here once verified.": "تُقدَّم الشهادات والوثائق الفنية عند الطلب وتُنشر هنا بعد التحقق منها.",
    "Certified Quality": "جودةٌ معتمدة",
    "Clear filters": "مسح عوامل التصفية",
    "Color": "اللون",
    "Colour": "اللون",
    "Colour consistency checks": "فحوصات تناسق اللون",
    "Confidence, Documented": "ثقةٌ موثَّقة",
    "Consistent colour batching": "تجميع دفعات بلونٍ متناسق",
    "Contact": "اتصل بنا",
    "Crafted by TopShelf Technology": "من تطوير TopShelf Technology",
    "Custom dimensions on request": "أبعادٌ مخصّصة عند الطلب",
    "Cutting & Calibration": "القص والمعايرة",
    "Dense and weather-resistant": "كثيفٌ ومقاوم للعوامل الجوية",
    "Dimensional accuracy": "دقة الأبعاد",
    "Documented Quality": "جودةٌ موثَّقة",
    "Documented inspection of colour consistency, dimensional accuracy and surface finish before packing. Custom finishes and sizes are available on request.": "فحصٌ موثَّق لتناسق اللون ودقة الأبعاد وتشطيب السطح قبل التغليف. تتوفّر تشطيبات وأحجام مخصّصة عند الطلب.",
    "Download Catalogue": "تحميل الكتالوج",
    "Download PDF": "تحميل ملف PDF",
    "Download our full bilingual stone & marble catalogue.": "حمّل كتالوج الحجر والرخام الكامل بلغتين.",
    "Email": "البريد الإلكتروني",
    "Engineered for": "مصمَّمٌ من أجل",
    "Enquire About This Stone": "استفسر عن هذا الحجر",
    "Equipped for scale and precision": "مجهَّزٌ للحجم والدقة",
    "Europe": "أوروبا",
    "Every batch is inspected for colour, dimension and finish before it leaves.": "تُفحص كل دفعة من حيث اللون والأبعاد والتشطيب قبل مغادرتها.",
    "Every block is selected for character and consistency, then cut, finished and packed to exacting export standards — so what you specify is exactly what arrives on site.": "تُنتقى كل كتلة حسب الطابع والتناسق، ثم تُقصّ وتُشطَّب وتُغلَّف وفق معايير تصدير دقيقة — لذا فإن ما تحدّده هو تماماً ما يصل إلى الموقع.",
    "Experienced export logistics and secure crating deliver Palestinian stone reliably to projects across the Gulf, Europe and beyond.": "خدماتٌ لوجستية متمرّسة وتغليفٌ آمن توصّل الحجر الفلسطيني بموثوقية إلى المشاريع في الخليج وأوروبا وما بعدها.",
    "Experienced logistics": "خدماتٌ لوجستية متمرّسة",
    "Explore": "استكشف",
    "Explore Products": "استكشف المنتجات",
    "Explore by Material": "استكشف حسب المادة",
    "Explore the Collection": "استكشف المجموعة",
    "Export Compliance": "الامتثال للتصدير",
    "Export Excellence": "تميُّزٌ في التصدير",
    "Export Inquiries": "استفسارات التصدير",
    "Export Markets": "أسواق التصدير",
    "Export Packing": "التغليف للتصدير",
    "Export Readiness": "الجاهزية للتصدير",
    "Export markets": "أسواق التصدير",
    "Export-grade crating": "تغليفٌ بمستوى التصدير",
    "Export-ready": "جاهزٌ للتصدير",
    "Featured Stone & Marble": "حجرٌ ورخامٌ مميّز",
    "Find Us": "موقعنا",
    "Finish": "التشطيب",
    "Finish types": "أنواع التشطيب",
    "Finish verification": "التحقق من التشطيب",
    "Finishes": "التشطيبات",
    "For over twenty years we have combined traditional Palestinian stone craft with modern processing to deliver consistent colour, calibrated thickness and reliable export quality.": "على مدى أكثر من عشرين عاماً، جمعنا بين حرفة الحجر الفلسطيني التقليدية والمعالجة الحديثة لتقديم لونٍ متناسق وسماكةٍ معايَرة وجودة تصدير موثوقة.",
    "From Local Craft to Global Supply": "من الحرفة المحلية إلى التوريد العالمي",
    "From Quarry to Quay": "من المحجر إلى الميناء",
    "From the historic quarries around Bethlehem, Al-Baron transforms raw Palestinian limestone and marble into precision-finished materials trusted on facades, floors and landmark interiors across the globe.": "من المحاجر التاريخية حول بيت لحم، يحوّل البارون الحجر الجيري والرخام الفلسطيني الخام إلى موادّ مُتقنة التشطيب، موثوقة في الواجهات والأرضيات والتصاميم الداخلية البارزة حول العالم.",
    "From the historic quarries around Bethlehem, Al-Baron turns raw limestone and marble into precision-finished materials trusted on landmark projects worldwide.": "من المحاجر التاريخية حول بيت لحم، يحوّل البارون الحجر الجيري والرخام الخام إلى موادّ مُتقنة التشطيب، موثوقة في المشاريع البارزة حول العالم.",
    "Full control from extraction to finishing and export packing ensures consistent color, thickness and quality across every order.": "تحكُّمٌ كامل من الاستخراج إلى التشطيب والتغليف للتصدير يضمن لوناً وسماكة وجودة متناسقة في كل طلب.",
    "Full ownership of the process from extraction to export.": "ملكيةٌ كاملة للعملية من الاستخراج إلى التصدير.",
    "Gallery": "المعرض",
    "Gallery images will appear here once products are published.": "ستظهر صور المعرض هنا بمجرد نشر المنتجات.",
    "Gang saws cut raw blocks into calibrated slabs with consistent thickness.": "تقطع مناشير الإطار الكتل الخام إلى ألواح معايَرة بسماكة متناسقة.",
    "Generations of stone craft rooted in the quarries of Bethlehem.": "أجيالٌ من حرفة الحجر متجذّرة في محاجر بيت لحم.",
    "Genuine Palestinian limestone and marble, quarried from the hills around Bethlehem — nothing imitated, nothing substituted.": "حجرٌ جيري ورخامٌ فلسطيني أصيل، مُستخرَج من تلال بيت لحم — لا تقليد ولا بدائل.",
    "Get in Touch": "تواصل معنا",
    "Get the Catalogue": "احصل على الكتالوج",
    "Global": "عالمي",
    "Global Delivery": "توصيلٌ عالمي",
    "Global delivery": "توصيلٌ عالمي",
    "Gulf (GCC)": "الخليج (دول مجلس التعاون)",
    "Heritage": "إرث",
    "Inspected before it ships": "مفحوصٌ قبل الشحن",
    "Inspection records for colour, dimension and finish.": "سجلّات فحص للّون والأبعاد والتشطيب.",
    "Large-format capability": "قدرةٌ على التنسيقات الكبيرة",
    "Let’s Talk": "لنتحدّث",
    "Let’s bring timeless stone to your next build.": "لنُضف حجراً خالداً إلى بنائك القادم.",
    "Levant": "بلاد الشام",
    "Location": "الموقع",
    "Machinery & Capacity": "الآلات والطاقة الإنتاجية",
    "Material": "المادة",
    "Material specifications available on request.": "المواصفات الفنية متوفّرة عند الطلب.",
    "Max slab length": "أقصى طول للّوح",
    "Modern gang saws, bridge cutters and finishing lines enable a broad range of formats, from standard tiles to large slabs and cut-to-size architectural pieces.": "مناشير إطار حديثة وآلات قص جسرية وخطوط تشطيب تتيح مجموعة واسعة من التنسيقات، من البلاط القياسي إلى الألواح الكبيرة والقطع المعمارية المقصوصة حسب المقاس.",
    "Modernised": "التحديث",
    "Natural Palestinian stone": "حجرٌ فلسطيني طبيعي",
    "Natural Stone & Marble": "حجرٌ ورخامٌ طبيعي",
    "Naturally warm, golden and cream tones": "درجاتٌ دافئة طبيعية ذهبية وكريمية",
    "News": "الأخبار",
    "News & Updates": "الأخبار والمستجدات",
    "Newsroom": "غرفة الأخبار",
    "No news yet": "لا توجد أخبار بعد",
    "No products match these filters": "لا توجد منتجات تطابق عوامل التصفية هذه",
    "No projects yet": "لا توجد مشاريع بعد",
    "North Africa": "شمال أفريقيا",
    "North America": "أمريكا الشمالية",
    "One accountable partner, every step of the way.": "شريكٌ واحد مسؤول في كل خطوة.",
    "Our Capabilities": "إمكاناتنا",
    "Our Journey": "رحلتنا",
    "Our Story": "قصتنا",
    "Our Values": "قيمنا",
    "Our project case studies will appear here soon.": "ستظهر دراسات حالة مشاريعنا هنا قريباً.",
    "Our vertically integrated operation — from extraction through cutting, finishing and export packing — gives buyers a single, accountable partner from quarry to quay.": "عمليتنا المتكاملة رأسياً — من الاستخراج إلى القص والتشطيب والتغليف للتصدير — تمنح المشترين شريكاً واحداً مسؤولاً من المحجر إلى الميناء.",
    "Packaging & supply": "التغليف والتوريد",
    "Packed to arrive perfectly": "مُغلَّفٌ ليصل بحالة مثالية",
    "Packing and documentation prepared to export standards.": "تغليفٌ ووثائق مُعدّة وفق معايير التصدير.",
    "Palestinian Stone": "الحجر الفلسطيني",
    "Palestinian stone": "حجرٌ فلسطيني",
    "Palestinian stone delivered to architects and developers across the world.": "حجرٌ فلسطيني يُوصَّل إلى المعماريين والمطوّرين حول العالم.",
    "Palestinian stone, delivered to architects, developers and traders across the globe.": "حجرٌ فلسطيني، يُوصَّل إلى المعماريين والمطوّرين والتجار حول العالم.",
    "Please check back soon for Al-Baron announcements and updates.": "يُرجى العودة قريباً لمتابعة إعلانات ومستجدات البارون.",
    "Polished, honed, brushed, bush-hammered and split-face finishes applied to spec.": "تشطيبات مصقولة ومجلوّة ومفرشاة ومطروقة ومشقوقة الوجه تُطبَّق حسب المواصفات.",
    "Precision": "الدقة",
    "Premium Palestinian natural stone & marble from Bethlehem — quarried, crafted and delivered for export projects worldwide.": "حجرٌ ورخامٌ فلسطيني طبيعي فاخر من بيت لحم — مُستخرَج ومُشكَّل ومُوصَّل لمشاريع التصدير حول العالم.",
    "Premium natural stone & marble — quarried, hand-finished and export-ready for architects, developers and stone traders worldwide.": "حجرٌ ورخامٌ طبيعي فاخر — مُستخرَج ومُشطَّب يدوياً وجاهز للتصدير للمعماريين والمطوّرين وتجار الحجر حول العالم.",
    "Pricing based on material, finish, quantity and destination": "التسعير بناءً على المادة والتشطيب والكمية والوجهة",
    "Primary": "الرئيسية",
    "Processes and packing built for demanding international specifications.": "عملياتٌ وتغليفٌ مصمَّمة للمواصفات الدولية الصارمة.",
    "Product code": "رمز المنتج",
    "Product filters": "عوامل تصفية المنتجات",
    "Production": "الإنتاج",
    "Project": "مشروع",
    "Projects": "المشاريع",
    "QA inspected": "مفحوصٌ لضمان الجودة",
    "Quality & Certifications": "الجودة والشهادات",
    "Quality Assurance": "ضمان الجودة",
    "Quality Inspection": "فحص الجودة",
    "Quarry Selection": "انتقاء المحجر",
    "Quarry to Quay": "من المحجر إلى الميناء",
    "Quarry-to-Quay Control": "تحكُّمٌ من المحجر إلى الميناء",
    "Read more": "اقرأ المزيد",
    "Refine": "تنقية",
    "Reliability": "الموثوقية",
    "Remove filter": "إزالة عامل التصفية",
    "Repeatable finishes": "تشطيباتٌ قابلة للتكرار",
    "Request a Quote": "اطلب عرض سعر",
    "Request samples, specifications and a quote.": "اطلب عينات ومواصفات وعرض سعر.",
    "Reset all": "إعادة ضبط الكل",
    "Rigorous selection, calibrated finishes and documented quality controls — ready for demanding international specifications.": "انتقاءٌ صارم وتشطيباتٌ معايَرة وضوابط جودة موثَّقة — جاهزة للمواصفات الدولية الصارمة.",
    "Rooted in": "متجذّرٌ في",
    "Samples and technical specifications on request": "العينات والمواصفات الفنية عند الطلب",
    "Scroll": "مرّر",
    "Secure crating and palletising to export standard for safe global delivery.": "تغليفٌ وتحميلٌ آمن على المنصّات وفق معيار التصدير لتوصيل عالمي آمن.",
    "Secure crating and palletising to export standard, with experienced logistics for reliable international delivery across the Gulf, Europe and beyond.": "تغليفٌ وتحميلٌ آمن على المنصّات وفق معيار التصدير، مع خدمات لوجستية متمرّسة لتوصيل دولي موثوق عبر الخليج وأوروبا وما بعدها.",
    "See Our Capabilities": "اطّلع على إمكاناتنا",
    "Selection at the quarry, block sawing, calibration, surface finishing and quality inspection — each stage is controlled to hold colour, dimension and finish tolerances across large orders.": "الانتقاء في المحجر، ونشر الكتل، والمعايرة، وتشطيب السطح، وفحص الجودة — تُضبط كل مرحلة للحفاظ على تفاوتات اللون والأبعاد والتشطيب في الطلبات الكبيرة.",
    "Send us your requirements": "أرسل لنا متطلباتك",
    "Signature Selection": "التشكيلة المميّزة",
    "Size": "المقاس",
    "Social": "التواصل الاجتماعي",
    "Social media": "وسائل التواصل الاجتماعي",
    "Specify with Confidence": "حدِّد بثقة",
    "Start Your Project": "ابدأ مشروعك",
    "Stone": "الحجر",
    "Stone & Marble Products": "منتجات الحجر والرخام",
    "Stone craft": "حرفة الحجر",
    "Stone finishing": "تشطيب الحجر",
    "Stone used": "الحجر المستخدَم",
    "Stone varieties": "أنواع الحجر",
    "Surface Finishing": "تشطيب السطح",
    "Surfaces, finishes and applications — a closer look at the character of Al-Baron natural stone.": "أسطحٌ وتشطيباتٌ واستخدامات — نظرةٌ أقرب إلى طابع حجر البارون الطبيعي.",
    "Technical Data": "البيانات الفنية",
    "Technical Data Sheets": "صحائف البيانات الفنية",
    "Tell us about your project and our export team will respond with samples, specifications and pricing.": "أخبرنا عن مشروعك وسيردّ فريق التصدير لدينا بالعينات والمواصفات والأسعار.",
    "Tell us about your project — material, finish and quantity — and our export team will respond with samples, specifications and pricing.": "أخبرنا عن مشروعك — المادة والتشطيب والكمية — وسيردّ فريق التصدير لدينا بالعينات والمواصفات والأسعار.",
    "That control is what lets us promise consistency at scale: the same colour, the same calibration and the same finish, order after order.": "هذا التحكُّم هو ما يتيح لنا ضمان التناسق على نطاق واسع: اللون نفسه، والمعايرة نفسها، والتشطيب نفسه، طلباً بعد طلب.",
    "The Collection": "المجموعة",
    "The Enduring Beauty of": "الجمال الخالد لـ",
    "The Process": "العملية",
    "The inquiry form is being configured.": "يجري إعداد نموذج الاستفسار.",
    "The limestone and marble of the Bethlehem hills has shaped the region’s architecture for centuries — warm, dense and enduring.": "شكّل الحجر الجيري والرخام في تلال بيت لحم عمارة المنطقة لقرون — دافئ وكثيف وخالد.",
    "The more detail you share, the faster we can quote accurately.": "كلما زادت التفاصيل التي تشاركها، أسرعنا في تقديم عرض سعر دقيق.",
    "Thickness": "السماكة",
    "Tiles, slabs & cut-to-size": "بلاطٌ وألواحٌ وقطعٌ حسب المقاس",
    "Toggle menu": "تبديل القائمة",
    "Traditional craft combined with modern sawing, calibration and finishing.": "حرفةٌ تقليدية ممزوجة بالنشر والمعايرة والتشطيب الحديث.",
    "Try adjusting or clearing your filters to see more of the collection.": "حاول تعديل عوامل التصفية أو مسحها لرؤية المزيد من المجموعة.",
    "Two decades of stone craft, refined for export.": "عقدان من حرفة الحجر، مصقولان للتصدير.",
    "Uses": "الاستخدامات",
    "Vertically Integrated": "تكاملٌ رأسي",
    "View All Products": "عرض جميع المنتجات",
    "View details": "عرض التفاصيل",
    "View project": "عرض المشروع",
    "Visual Portfolio": "معرض الأعمال المرئي",
    "What We Stand For": "ما نؤمن به",
    "What you specify is what arrives — packed to export standard and delivered on schedule to projects worldwide.": "ما تحدّده هو ما يصل — مُغلَّف وفق معيار التصدير ومُوصَّل في موعده إلى المشاريع حول العالم.",
    "WhatsApp": "واتساب",
    "Where We Ship": "إلى أين نشحن",
    "Who We Are": "من نحن",
    "Why Al-Baron": "لماذا البارون",
    "Why Bethlehem Stone": "لماذا حجر بيت لحم",
    "Work With Us": "اعمل معنا",
    "Year": "السنة",
    "Years of craft": "سنوات من الحرفة",
    # Route titles (passed through t()).
    "Products": "المنتجات",
    "Company": "الشركة",
    "Al-Baron — Natural Stone & Marble": "البارون — حجرٌ ورخامٌ طبيعي",
    "Capabilities & Certifications": "الإمكانات والشهادات",
    "Request a Quote": "اطلب عرض سعر",
}


def po_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    sources = set(json.load(open('/tmp/strings.json', encoding='utf-8')))
    # Include the extra route titles that are not in the extracted template set.
    sources |= {"Products", "Company", "Al-Baron — Natural Stone & Marble",
                "Capabilities & Certifications", "Request a Quote"}

    missing = sorted(s for s in sources if s not in AR)
    if missing:
        print("WARNING: untranslated sources:", file=sys.stderr)
        for m in missing:
            print("  -", m, file=sys.stderr)

    out = ['msgid ""', 'msgstr ""',
           '"Project-Id-Version: albaron\\n"',
           '"MIME-Version: 1.0\\n"',
           '"Content-Type: text/plain; charset=UTF-8\\n"',
           '"Content-Transfer-Encoding: 8bit\\n"',
           '"Language: ar\\n"',
           '"Plural-Forms: nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 ? 4 : 5);\\n"',
           '']
    for src in sorted(sources):
        ar = AR.get(src)
        if not ar:
            continue
        out.append(f'msgid "{po_escape(src)}"')
        out.append(f'msgstr "{po_escape(ar)}"')
        out.append('')

    dest = os.path.join(os.path.dirname(__file__), 'translations', 'albaron.ar.po')
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    open(dest, 'w', encoding='utf-8').write('\n'.join(out))
    print(f"Wrote {dest} with {sum(1 for s in sources if s in AR)} translations; {len(missing)} missing.")


if __name__ == '__main__':
    main()
